[workspace]
authors = ["KEKE046 <zhoukexing@pku.edu.cn>"]
channels = ["conda-forge"]
name = "chisel-cores"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "chisel-cores"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-rattler-build",  version = "0.1.*"}

[tasks]
upload = "rattler-build upload anaconda --owner KEKE046 ./chisel-cores-*.conda --force"

[dependencies]
sbt = ">=1.10.2,<2"
dtc = ">=1.7.2,<2"
