[workspace]
authors = ["KEKE046 <zhoukexing@pku.edu.cn>"]
channels = [
    "ucb-bar",
    "conda-forge",
    "litex-hub"
]
name = "ksim-bench"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sbt = ">=1.10.2,<2"
