package:
  name: chisel-cores
  version: "0.3.1"

source:
  path: .
  use_gitignore: true

build:
  number: 1
  script: |
    patch -d rocket-chip -p 1 < $PWD/patches/rocket-chip.patch
    patch -d riscv-boom  -p 1 < $PWD/patches/riscv-boom.patch
    patch -d rocket-chip-blocks -p 1 < $PWD/patches/rocket-chip-blocks.patch
    sbt assembly
    install -Dm755 utils/chisel-cores $PREFIX/bin/chisel-cores
    install -Dm644 target/scala-2.13/chisel-cores-assembly-1.6.jar $PREFIX/bin/chisel-cores.jar

requirements:
  build:
    - sbt
    - patch
  run:
    - openjdk
    - dtc
